# Site settings
title: Vox of Victor
description: Welcome to Victor's Domain
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: ''
google_analytics: UA-90713500-1
# disqus_shortname: 'your-disqus-name'
rss: false

author:
  name: Victor Ng
  email: victorng8@gmail.com
  twitter_username:
  facebook_username:
  github_username:  victorng8
  linkedin_username:  victortzng

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
